import type { Metadata } from "next";
import "./globals.css";
import { AppBar } from "./component/isolated/appBar";
import { Box } from "@mui/material";
import ThemeWrapper from "./themeWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ThemeWrapper>
          <AppBar />
          <Box>{children}</Box>
        </ThemeWrapper>
      </body>
    </html>
  );
}
